// <auto-generated />
using CollaborativeDrawingBoard.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollaborativeDrawingBoard.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231226123806_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollaborativeDrawingBoard.Server.Models.DrawingBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DrawingBoards");
                });

            modelBuilder.Entity("CollaborativeDrawingBoard.Server.Models.Stroke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrawingBoardId")
                        .HasColumnType("int");

                    b.Property<int>("EndPointX")
                        .HasColumnType("int");

                    b.Property<int>("EndPointY")
                        .HasColumnType("int");

                    b.Property<int>("StartPointX")
                        .HasColumnType("int");

                    b.Property<int>("StartPointY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawingBoardId");

                    b.ToTable("Strokes");
                });

            modelBuilder.Entity("CollaborativeDrawingBoard.Server.Models.Stroke", b =>
                {
                    b.HasOne("CollaborativeDrawingBoard.Server.Models.DrawingBoard", "DrawingBoard")
                        .WithMany("Strokes")
                        .HasForeignKey("DrawingBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingBoard");
                });

            modelBuilder.Entity("CollaborativeDrawingBoard.Server.Models.DrawingBoard", b =>
                {
                    b.Navigation("Strokes");
                });
#pragma warning restore 612, 618
        }
    }
}
